version: "3"
services:
  db:
    image: postgres
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: process.env.PG_PASS
      POSTGRES_USER: process.env.PG_USER
      POSTGRES_DB: process.env.PG_DATABASE
    ports:
        - "5432:5432"
networks:
  webnet: